langchain4j:
  # AI provider configuration
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY}
      model-name: ${OPENAI_MODEL_NAME:gpt-4o}
      # log-requests: true
      # log-responses: true
