# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json
name: ai-nutrition-planner
metadata:
  template: ai-nutrition-planner
services:
  langchain4j:
    project: ./langchain4j
    host: containerapp
    language: java
    hooks:
      prepackage:
        shell: sh
        run: cd langchain4j && ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=ai-nutrition-planer-langchain4j
    docker:
      image: ai-nutrition-planer-langchain4j
  spring-ai:
    project: ./spring-ai
    host: containerapp
    language: java
    hooks:
      prepackage:
        shell: sh
        run: cd spring-ai && ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=ai-nutrition-planer-spring-ai
    docker:
      image: ai-nutrition-planer-spring-ai
  embabel:
    project: ./embabel
    host: containerapp
    language: java
    hooks:
      prepackage:
        shell: sh
        run: cd embabel && ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=ai-nutrition-planer-embabel
    docker:
      image: ai-nutrition-planer-embabel