spring:
  application.name: nutrition-planner
  security.user:
      password: 123456
      name: alice
  ai:
    chat.client.observations.log-completion: true
    tools.observations.include-content: true
    mcp.server.protocol: STREAMABLE

embabel:
  agent.platform.process-type: CONCURRENT
  models.default-llm: gpt-5-nano
  agent.platform.llm-operations.prompts.default-timeout: 180s
  observability:
    service-name: ${spring.application.name}
    trace-http-details: true

logging.level:
    com.embabel.agent: DEBUG
    io.modelcontextprotocol.server: DEBUG

management:
  endpoints.web.exposure.include: "*"
  endpoint.env.show-values: ALWAYS
  otlp.metrics.export.enabled: false

nutrition-planner:
  user-profiles:
    - name: alice
      dietary-restrictions:
        - vegetarian
      health-goals:
        - weight-loss
        - improve-energy
      daily-calorie-target: 1800
      allergies:
        - nuts
      disliked-ingredients:
        - cilantro
        - olives
